grpc:
  server:
    port: 0
#    # 客户端配置
#    GLOBAL:
#      address: 'static://127.0.0.1:9090'
#      enable-keep-alive: true
#      keep-alive-without-calls: true
#      negotiation-type: plaintext
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: zhongdongsheng
    password: DS@71b6e2b5b0c5390c1f9ec2c918d7d686
    url: jdbc:mysql://localhost:3306/tutu?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
  application:
    name: database-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        enabled: true
  redis:
    host: 192.168.1.127
    port: 6379
    username:
    password:
    lettuce:
      pool:
        max-active: 8 # 最大连接数
        max-idle: 8 # 最大空闲连接
        min-idle: 0 # 最小空闲连接
        max-wait: 1ms # 当连接池耗尽后，抛出异常前最大阻塞时间
  ######kafka配置######
  kafka:
    producer:
      acks: 1
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 3
      batch-size: 16384
      buffer-memory: 33554432
    consumer:
      group-id: dataSaveGroup
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: latest
      enable-auto-commit: false
    listener:
      ack-mode: manual
      type: batch
    bootstrap-servers: 192.168.1.127:9092
mybatis:
  mapper-locations: com/zds/mapper/*.xml
  type-aliases-package: com.zds.entity
  configuration:
    map-underscore-to-camel-case: true

logging:
  config: classpath:logback-spring.xml


