spring:
  application:
    name: api-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true # 开启通过服务名进行服务调用
          lower-case-service-id: true # 服务名不区分大小写
      routes:
#        - id: database-service
#          uri: lb://database-service
#          predicates:
#            - Path=/**
        # id全局唯一即可
#        - id: service-provider
#          uri: lb://service-provider
#          predicates:
#            - Path=/**
        - id: service-consumer
          uri: lb://service-consumer
          predicates:
            - Path=/**
      default-filters:

  auth:
    whiteIP:
      - 192.168.1.128
    whiteUrl:
      - /customer/query1
      - /customer/query2

server:
  port: 9200

