server:
  port: 8080
spring:
  application:
    name: module-jpa
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: zhongdongsheng
    password: 123456
    url: jdbc:mysql://localhost:3306/tutu?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true