// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CustomerInfoService.proto_1

package com.zds.grpc.grpc;

public final class CustomerInfoProto {
  private CustomerInfoProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_CustomerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_CustomerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_CustomerResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_CustomerResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_CustomerInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_CustomerInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\031CustomerInfoService.proto\022\004grpc\"\037\n\017Cus" +
      "tomerRequest\022\014\n\004name\030\001 \001(\t\"B\n\020CustomerRe" +
      "sponse\022\014\n\004code\030\001 \001(\t\022 \n\004data\030\002 \001(\0132\022.grp" +
      "c.CustomerInfo\")\n\014CustomerInfo\022\014\n\004name\030\001" +
      " \001(\t\022\013\n\003sex\030\002 \001(\t2_\n\023CustomerInfoService" +
      "\022H\n\025GetCustomerInfoByName\022\025.grpc.Custome" +
      "rRequest\032\026.grpc.CustomerResponse\"\000B)\n\022co" +
      "m.zds.proto.grpcB\021CustomerInfoProtoP\001b\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_grpc_CustomerRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_grpc_CustomerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_CustomerRequest_descriptor,
        new String[] { "Name", });
    internal_static_grpc_CustomerResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_grpc_CustomerResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_CustomerResponse_descriptor,
        new String[] { "Code", "Data", });
    internal_static_grpc_CustomerInfo_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_grpc_CustomerInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_CustomerInfo_descriptor,
        new String[] { "Name", "Sex", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
