// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CustomerInfoService.proto_1

package com.zds.grpc.grpc;

public interface CustomerInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.CustomerInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string sex = 2;</code>
   * @return The sex.
   */
  String getSex();
  /**
   * <code>string sex = 2;</code>
   * @return The bytes for sex.
   */
  com.google.protobuf.ByteString
      getSexBytes();
}
