// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CustomerInfoService.proto_1

package com.zds.grpc.grpc;

public interface CustomerRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.CustomerRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
