// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CustomerInfoService.proto

package com.zds.grpc.api;

public interface CustomerResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.CustomerResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string code = 1;</code>
   * @return The code.
   */
  String getCode();
  /**
   * <code>string code = 1;</code>
   * @return The bytes for code.
   */
  com.google.protobuf.ByteString
      getCodeBytes();

  /**
   * <code>.grpc.CustomerInfo data = 2;</code>
   * @return Whether the data field is set.
   */
  boolean hasData();
  /**
   * <code>.grpc.CustomerInfo data = 2;</code>
   * @return The data.
   */
  CustomerInfo getData();
  /**
   * <code>.grpc.CustomerInfo data = 2;</code>
   */
  CustomerInfoOrBuilder getDataOrBuilder();
}
