// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CustomerInfoService.proto

package com.zds.grpc.api;

/**
 * Protobuf type {@code grpc.CustomerInfo}
 */
public final class CustomerInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:grpc.CustomerInfo)
    CustomerInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CustomerInfo.newBuilder() to construct.
  private CustomerInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CustomerInfo() {
    customerName_ = "";
    password_ = "";
    customerSex_ = "";
    customerTel_ = "";
    customerEmail_ = "";
    customerAddress_ = "";
    createTime_ = "";
    updateTime_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new CustomerInfo();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CustomerInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            String s = input.readStringRequireUtf8();

            customerName_ = s;
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            password_ = s;
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();

            customerSex_ = s;
            break;
          }
          case 34: {
            String s = input.readStringRequireUtf8();

            customerTel_ = s;
            break;
          }
          case 42: {
            String s = input.readStringRequireUtf8();

            customerEmail_ = s;
            break;
          }
          case 50: {
            String s = input.readStringRequireUtf8();

            customerAddress_ = s;
            break;
          }
          case 58: {
            String s = input.readStringRequireUtf8();

            createTime_ = s;
            break;
          }
          case 66: {
            String s = input.readStringRequireUtf8();

            updateTime_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return CustomerInfoProto.internal_static_grpc_CustomerInfo_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return CustomerInfoProto.internal_static_grpc_CustomerInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            CustomerInfo.class, Builder.class);
  }

  public static final int CUSTOMER_NAME_FIELD_NUMBER = 1;
  private volatile Object customerName_;
  /**
   * <code>string customer_name = 1;</code>
   * @return The customerName.
   */
  @Override
  public String getCustomerName() {
    Object ref = customerName_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      customerName_ = s;
      return s;
    }
  }
  /**
   * <code>string customer_name = 1;</code>
   * @return The bytes for customerName.
   */
  @Override
  public com.google.protobuf.ByteString
      getCustomerNameBytes() {
    Object ref = customerName_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      customerName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PASSWORD_FIELD_NUMBER = 2;
  private volatile Object password_;
  /**
   * <code>string password = 2;</code>
   * @return The password.
   */
  @Override
  public String getPassword() {
    Object ref = password_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      password_ = s;
      return s;
    }
  }
  /**
   * <code>string password = 2;</code>
   * @return The bytes for password.
   */
  @Override
  public com.google.protobuf.ByteString
      getPasswordBytes() {
    Object ref = password_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      password_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CUSTOMER_SEX_FIELD_NUMBER = 3;
  private volatile Object customerSex_;
  /**
   * <code>string customer_sex = 3;</code>
   * @return The customerSex.
   */
  @Override
  public String getCustomerSex() {
    Object ref = customerSex_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      customerSex_ = s;
      return s;
    }
  }
  /**
   * <code>string customer_sex = 3;</code>
   * @return The bytes for customerSex.
   */
  @Override
  public com.google.protobuf.ByteString
      getCustomerSexBytes() {
    Object ref = customerSex_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      customerSex_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CUSTOMER_TEL_FIELD_NUMBER = 4;
  private volatile Object customerTel_;
  /**
   * <code>string customer_tel = 4;</code>
   * @return The customerTel.
   */
  @Override
  public String getCustomerTel() {
    Object ref = customerTel_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      customerTel_ = s;
      return s;
    }
  }
  /**
   * <code>string customer_tel = 4;</code>
   * @return The bytes for customerTel.
   */
  @Override
  public com.google.protobuf.ByteString
      getCustomerTelBytes() {
    Object ref = customerTel_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      customerTel_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CUSTOMER_EMAIL_FIELD_NUMBER = 5;
  private volatile Object customerEmail_;
  /**
   * <code>string customer_email = 5;</code>
   * @return The customerEmail.
   */
  @Override
  public String getCustomerEmail() {
    Object ref = customerEmail_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      customerEmail_ = s;
      return s;
    }
  }
  /**
   * <code>string customer_email = 5;</code>
   * @return The bytes for customerEmail.
   */
  @Override
  public com.google.protobuf.ByteString
      getCustomerEmailBytes() {
    Object ref = customerEmail_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      customerEmail_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CUSTOMER_ADDRESS_FIELD_NUMBER = 6;
  private volatile Object customerAddress_;
  /**
   * <code>string customer_address = 6;</code>
   * @return The customerAddress.
   */
  @Override
  public String getCustomerAddress() {
    Object ref = customerAddress_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      customerAddress_ = s;
      return s;
    }
  }
  /**
   * <code>string customer_address = 6;</code>
   * @return The bytes for customerAddress.
   */
  @Override
  public com.google.protobuf.ByteString
      getCustomerAddressBytes() {
    Object ref = customerAddress_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      customerAddress_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CREATE_TIME_FIELD_NUMBER = 7;
  private volatile Object createTime_;
  /**
   * <code>string create_time = 7;</code>
   * @return The createTime.
   */
  @Override
  public String getCreateTime() {
    Object ref = createTime_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      createTime_ = s;
      return s;
    }
  }
  /**
   * <code>string create_time = 7;</code>
   * @return The bytes for createTime.
   */
  @Override
  public com.google.protobuf.ByteString
      getCreateTimeBytes() {
    Object ref = createTime_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      createTime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int UPDATE_TIME_FIELD_NUMBER = 8;
  private volatile Object updateTime_;
  /**
   * <code>string update_time = 8;</code>
   * @return The updateTime.
   */
  @Override
  public String getUpdateTime() {
    Object ref = updateTime_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      updateTime_ = s;
      return s;
    }
  }
  /**
   * <code>string update_time = 8;</code>
   * @return The bytes for updateTime.
   */
  @Override
  public com.google.protobuf.ByteString
      getUpdateTimeBytes() {
    Object ref = updateTime_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      updateTime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(customerName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, customerName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(password_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, password_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(customerSex_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, customerSex_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(customerTel_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, customerTel_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(customerEmail_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, customerEmail_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(customerAddress_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, customerAddress_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(createTime_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, createTime_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(updateTime_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, updateTime_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(customerName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, customerName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(password_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, password_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(customerSex_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, customerSex_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(customerTel_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, customerTel_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(customerEmail_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, customerEmail_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(customerAddress_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, customerAddress_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(createTime_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, createTime_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(updateTime_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, updateTime_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof CustomerInfo)) {
      return super.equals(obj);
    }
    CustomerInfo other = (CustomerInfo) obj;

    if (!getCustomerName()
        .equals(other.getCustomerName())) return false;
    if (!getPassword()
        .equals(other.getPassword())) return false;
    if (!getCustomerSex()
        .equals(other.getCustomerSex())) return false;
    if (!getCustomerTel()
        .equals(other.getCustomerTel())) return false;
    if (!getCustomerEmail()
        .equals(other.getCustomerEmail())) return false;
    if (!getCustomerAddress()
        .equals(other.getCustomerAddress())) return false;
    if (!getCreateTime()
        .equals(other.getCreateTime())) return false;
    if (!getUpdateTime()
        .equals(other.getUpdateTime())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CUSTOMER_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getCustomerName().hashCode();
    hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
    hash = (53 * hash) + getPassword().hashCode();
    hash = (37 * hash) + CUSTOMER_SEX_FIELD_NUMBER;
    hash = (53 * hash) + getCustomerSex().hashCode();
    hash = (37 * hash) + CUSTOMER_TEL_FIELD_NUMBER;
    hash = (53 * hash) + getCustomerTel().hashCode();
    hash = (37 * hash) + CUSTOMER_EMAIL_FIELD_NUMBER;
    hash = (53 * hash) + getCustomerEmail().hashCode();
    hash = (37 * hash) + CUSTOMER_ADDRESS_FIELD_NUMBER;
    hash = (53 * hash) + getCustomerAddress().hashCode();
    hash = (37 * hash) + CREATE_TIME_FIELD_NUMBER;
    hash = (53 * hash) + getCreateTime().hashCode();
    hash = (37 * hash) + UPDATE_TIME_FIELD_NUMBER;
    hash = (53 * hash) + getUpdateTime().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static CustomerInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CustomerInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CustomerInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CustomerInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CustomerInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CustomerInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CustomerInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static CustomerInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static CustomerInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static CustomerInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static CustomerInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static CustomerInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(CustomerInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code grpc.CustomerInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:grpc.CustomerInfo)
      CustomerInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CustomerInfoProto.internal_static_grpc_CustomerInfo_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CustomerInfoProto.internal_static_grpc_CustomerInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CustomerInfo.class, Builder.class);
    }

    // Construct using com.zds.grpc.api.CustomerInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      customerName_ = "";

      password_ = "";

      customerSex_ = "";

      customerTel_ = "";

      customerEmail_ = "";

      customerAddress_ = "";

      createTime_ = "";

      updateTime_ = "";

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return CustomerInfoProto.internal_static_grpc_CustomerInfo_descriptor;
    }

    @Override
    public CustomerInfo getDefaultInstanceForType() {
      return CustomerInfo.getDefaultInstance();
    }

    @Override
    public CustomerInfo build() {
      CustomerInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public CustomerInfo buildPartial() {
      CustomerInfo result = new CustomerInfo(this);
      result.customerName_ = customerName_;
      result.password_ = password_;
      result.customerSex_ = customerSex_;
      result.customerTel_ = customerTel_;
      result.customerEmail_ = customerEmail_;
      result.customerAddress_ = customerAddress_;
      result.createTime_ = createTime_;
      result.updateTime_ = updateTime_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof CustomerInfo) {
        return mergeFrom((CustomerInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(CustomerInfo other) {
      if (other == CustomerInfo.getDefaultInstance()) return this;
      if (!other.getCustomerName().isEmpty()) {
        customerName_ = other.customerName_;
        onChanged();
      }
      if (!other.getPassword().isEmpty()) {
        password_ = other.password_;
        onChanged();
      }
      if (!other.getCustomerSex().isEmpty()) {
        customerSex_ = other.customerSex_;
        onChanged();
      }
      if (!other.getCustomerTel().isEmpty()) {
        customerTel_ = other.customerTel_;
        onChanged();
      }
      if (!other.getCustomerEmail().isEmpty()) {
        customerEmail_ = other.customerEmail_;
        onChanged();
      }
      if (!other.getCustomerAddress().isEmpty()) {
        customerAddress_ = other.customerAddress_;
        onChanged();
      }
      if (!other.getCreateTime().isEmpty()) {
        createTime_ = other.createTime_;
        onChanged();
      }
      if (!other.getUpdateTime().isEmpty()) {
        updateTime_ = other.updateTime_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      CustomerInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (CustomerInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Object customerName_ = "";
    /**
     * <code>string customer_name = 1;</code>
     * @return The customerName.
     */
    public String getCustomerName() {
      Object ref = customerName_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        customerName_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string customer_name = 1;</code>
     * @return The bytes for customerName.
     */
    public com.google.protobuf.ByteString
        getCustomerNameBytes() {
      Object ref = customerName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        customerName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string customer_name = 1;</code>
     * @param value The customerName to set.
     * @return This builder for chaining.
     */
    public Builder setCustomerName(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      customerName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string customer_name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCustomerName() {
      
      customerName_ = getDefaultInstance().getCustomerName();
      onChanged();
      return this;
    }
    /**
     * <code>string customer_name = 1;</code>
     * @param value The bytes for customerName to set.
     * @return This builder for chaining.
     */
    public Builder setCustomerNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      customerName_ = value;
      onChanged();
      return this;
    }

    private Object password_ = "";
    /**
     * <code>string password = 2;</code>
     * @return The password.
     */
    public String getPassword() {
      Object ref = password_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        password_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string password = 2;</code>
     * @return The bytes for password.
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      Object ref = password_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string password = 2;</code>
     * @param value The password to set.
     * @return This builder for chaining.
     */
    public Builder setPassword(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      password_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string password = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPassword() {
      
      password_ = getDefaultInstance().getPassword();
      onChanged();
      return this;
    }
    /**
     * <code>string password = 2;</code>
     * @param value The bytes for password to set.
     * @return This builder for chaining.
     */
    public Builder setPasswordBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      password_ = value;
      onChanged();
      return this;
    }

    private Object customerSex_ = "";
    /**
     * <code>string customer_sex = 3;</code>
     * @return The customerSex.
     */
    public String getCustomerSex() {
      Object ref = customerSex_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        customerSex_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string customer_sex = 3;</code>
     * @return The bytes for customerSex.
     */
    public com.google.protobuf.ByteString
        getCustomerSexBytes() {
      Object ref = customerSex_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        customerSex_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string customer_sex = 3;</code>
     * @param value The customerSex to set.
     * @return This builder for chaining.
     */
    public Builder setCustomerSex(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      customerSex_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string customer_sex = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCustomerSex() {
      
      customerSex_ = getDefaultInstance().getCustomerSex();
      onChanged();
      return this;
    }
    /**
     * <code>string customer_sex = 3;</code>
     * @param value The bytes for customerSex to set.
     * @return This builder for chaining.
     */
    public Builder setCustomerSexBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      customerSex_ = value;
      onChanged();
      return this;
    }

    private Object customerTel_ = "";
    /**
     * <code>string customer_tel = 4;</code>
     * @return The customerTel.
     */
    public String getCustomerTel() {
      Object ref = customerTel_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        customerTel_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string customer_tel = 4;</code>
     * @return The bytes for customerTel.
     */
    public com.google.protobuf.ByteString
        getCustomerTelBytes() {
      Object ref = customerTel_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        customerTel_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string customer_tel = 4;</code>
     * @param value The customerTel to set.
     * @return This builder for chaining.
     */
    public Builder setCustomerTel(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      customerTel_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string customer_tel = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearCustomerTel() {
      
      customerTel_ = getDefaultInstance().getCustomerTel();
      onChanged();
      return this;
    }
    /**
     * <code>string customer_tel = 4;</code>
     * @param value The bytes for customerTel to set.
     * @return This builder for chaining.
     */
    public Builder setCustomerTelBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      customerTel_ = value;
      onChanged();
      return this;
    }

    private Object customerEmail_ = "";
    /**
     * <code>string customer_email = 5;</code>
     * @return The customerEmail.
     */
    public String getCustomerEmail() {
      Object ref = customerEmail_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        customerEmail_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string customer_email = 5;</code>
     * @return The bytes for customerEmail.
     */
    public com.google.protobuf.ByteString
        getCustomerEmailBytes() {
      Object ref = customerEmail_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        customerEmail_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string customer_email = 5;</code>
     * @param value The customerEmail to set.
     * @return This builder for chaining.
     */
    public Builder setCustomerEmail(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      customerEmail_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string customer_email = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearCustomerEmail() {
      
      customerEmail_ = getDefaultInstance().getCustomerEmail();
      onChanged();
      return this;
    }
    /**
     * <code>string customer_email = 5;</code>
     * @param value The bytes for customerEmail to set.
     * @return This builder for chaining.
     */
    public Builder setCustomerEmailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      customerEmail_ = value;
      onChanged();
      return this;
    }

    private Object customerAddress_ = "";
    /**
     * <code>string customer_address = 6;</code>
     * @return The customerAddress.
     */
    public String getCustomerAddress() {
      Object ref = customerAddress_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        customerAddress_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string customer_address = 6;</code>
     * @return The bytes for customerAddress.
     */
    public com.google.protobuf.ByteString
        getCustomerAddressBytes() {
      Object ref = customerAddress_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        customerAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string customer_address = 6;</code>
     * @param value The customerAddress to set.
     * @return This builder for chaining.
     */
    public Builder setCustomerAddress(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      customerAddress_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string customer_address = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearCustomerAddress() {
      
      customerAddress_ = getDefaultInstance().getCustomerAddress();
      onChanged();
      return this;
    }
    /**
     * <code>string customer_address = 6;</code>
     * @param value The bytes for customerAddress to set.
     * @return This builder for chaining.
     */
    public Builder setCustomerAddressBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      customerAddress_ = value;
      onChanged();
      return this;
    }

    private Object createTime_ = "";
    /**
     * <code>string create_time = 7;</code>
     * @return The createTime.
     */
    public String getCreateTime() {
      Object ref = createTime_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        createTime_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string create_time = 7;</code>
     * @return The bytes for createTime.
     */
    public com.google.protobuf.ByteString
        getCreateTimeBytes() {
      Object ref = createTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        createTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string create_time = 7;</code>
     * @param value The createTime to set.
     * @return This builder for chaining.
     */
    public Builder setCreateTime(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      createTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string create_time = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearCreateTime() {
      
      createTime_ = getDefaultInstance().getCreateTime();
      onChanged();
      return this;
    }
    /**
     * <code>string create_time = 7;</code>
     * @param value The bytes for createTime to set.
     * @return This builder for chaining.
     */
    public Builder setCreateTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      createTime_ = value;
      onChanged();
      return this;
    }

    private Object updateTime_ = "";
    /**
     * <code>string update_time = 8;</code>
     * @return The updateTime.
     */
    public String getUpdateTime() {
      Object ref = updateTime_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        updateTime_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string update_time = 8;</code>
     * @return The bytes for updateTime.
     */
    public com.google.protobuf.ByteString
        getUpdateTimeBytes() {
      Object ref = updateTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        updateTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string update_time = 8;</code>
     * @param value The updateTime to set.
     * @return This builder for chaining.
     */
    public Builder setUpdateTime(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      updateTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string update_time = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearUpdateTime() {
      
      updateTime_ = getDefaultInstance().getUpdateTime();
      onChanged();
      return this;
    }
    /**
     * <code>string update_time = 8;</code>
     * @param value The bytes for updateTime to set.
     * @return This builder for chaining.
     */
    public Builder setUpdateTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      updateTime_ = value;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:grpc.CustomerInfo)
  }

  // @@protoc_insertion_point(class_scope:grpc.CustomerInfo)
  private static final CustomerInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new CustomerInfo();
  }

  public static CustomerInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CustomerInfo>
      PARSER = new com.google.protobuf.AbstractParser<CustomerInfo>() {
    @Override
    public CustomerInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CustomerInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CustomerInfo> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<CustomerInfo> getParserForType() {
    return PARSER;
  }

  @Override
  public CustomerInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

