// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CustomerInfoService.proto

package com.zds.grpc.api;

public interface CustomerRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.CustomerRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string customer_name = 1;</code>
   * @return The customerName.
   */
  String getCustomerName();
  /**
   * <code>string customer_name = 1;</code>
   * @return The bytes for customerName.
   */
  com.google.protobuf.ByteString
      getCustomerNameBytes();

  /**
   * <code>string password = 2;</code>
   * @return The password.
   */
  String getPassword();
  /**
   * <code>string password = 2;</code>
   * @return The bytes for password.
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <code>string customer_sex = 3;</code>
   * @return The customerSex.
   */
  String getCustomerSex();
  /**
   * <code>string customer_sex = 3;</code>
   * @return The bytes for customerSex.
   */
  com.google.protobuf.ByteString
      getCustomerSexBytes();

  /**
   * <code>string customer_tel = 4;</code>
   * @return The customerTel.
   */
  String getCustomerTel();
  /**
   * <code>string customer_tel = 4;</code>
   * @return The bytes for customerTel.
   */
  com.google.protobuf.ByteString
      getCustomerTelBytes();

  /**
   * <code>string customer_email = 5;</code>
   * @return The customerEmail.
   */
  String getCustomerEmail();
  /**
   * <code>string customer_email = 5;</code>
   * @return The bytes for customerEmail.
   */
  com.google.protobuf.ByteString
      getCustomerEmailBytes();

  /**
   * <code>string customer_address = 6;</code>
   * @return The customerAddress.
   */
  String getCustomerAddress();
  /**
   * <code>string customer_address = 6;</code>
   * @return The bytes for customerAddress.
   */
  com.google.protobuf.ByteString
      getCustomerAddressBytes();
}
