// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CustomerInfoService.proto

package com.zds.grpc.api;

public final class CustomerInfoProto {
  private CustomerInfoProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_CustomerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_CustomerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_CustomerResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_CustomerResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_CustomerInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_CustomerInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\031CustomerInfoService.proto\022\004grpc\"\230\001\n\017Cu" +
      "stomerRequest\022\025\n\rcustomer_name\030\001 \001(\t\022\020\n\010" +
      "password\030\002 \001(\t\022\024\n\014customer_sex\030\003 \001(\t\022\024\n\014" +
      "customer_tel\030\004 \001(\t\022\026\n\016customer_email\030\005 \001" +
      "(\t\022\030\n\020customer_address\030\006 \001(\t\"B\n\020Customer" +
      "Response\022\014\n\004code\030\001 \001(\t\022 \n\004data\030\002 \001(\0132\022.g" +
      "rpc.CustomerInfo\"\277\001\n\014CustomerInfo\022\025\n\rcus" +
      "tomer_name\030\001 \001(\t\022\020\n\010password\030\002 \001(\t\022\024\n\014cu" +
      "stomer_sex\030\003 \001(\t\022\024\n\014customer_tel\030\004 \001(\t\022\026" +
      "\n\016customer_email\030\005 \001(\t\022\030\n\020customer_addre" +
      "ss\030\006 \001(\t\022\023\n\013create_time\030\007 \001(\t\022\023\n\013update_" +
      "time\030\010 \001(\t2\244\001\n\023CustomerInfoService\022H\n\025Ge" +
      "tCustomerInfoByName\022\025.grpc.CustomerReque" +
      "st\032\026.grpc.CustomerResponse\"\000\022C\n\020SaveCust" +
      "omerInfo\022\025.grpc.CustomerRequest\032\026.grpc.C" +
      "ustomerResponse\"\000B\'\n\020com.zds.grpc.apiB\021C" +
      "ustomerInfoProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_grpc_CustomerRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_grpc_CustomerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_CustomerRequest_descriptor,
        new String[] { "CustomerName", "Password", "CustomerSex", "CustomerTel", "CustomerEmail", "CustomerAddress", });
    internal_static_grpc_CustomerResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_grpc_CustomerResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_CustomerResponse_descriptor,
        new String[] { "Code", "Data", });
    internal_static_grpc_CustomerInfo_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_grpc_CustomerInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_CustomerInfo_descriptor,
        new String[] { "CustomerName", "Password", "CustomerSex", "CustomerTel", "CustomerEmail", "CustomerAddress", "CreateTime", "UpdateTime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
